# Generated by Django 5.1.7 on 2025-03-13 02:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='stars',
            field=models.CharField(choices=[('1', '1 - Very Bad'), ('2', '2 - Bad'), ('3', '3 - Normal'), ('4', '4 - Good'), ('5', '5 - Perfect')], max_length=10),
        ),
    ]
